### ISSUE TITLE
Requesting explanation for transformation of waypoints before calculation of control points

### ISSUE THREAD

**Issue by indraneelpatil** [MithunNallana/path-smoothing#2]
Hello! 
Thanks for this implementation.  I am a little confused on why this step is needed? I could not find this step anywhere in the paper.
` % build transformation matrix to transform coordinates  
    % from global to local and local to global
    rotationMat     = [ut,un,ub];
    positionMat     = w1;
    transformMat    = [[rotationMat;zeros(1,3)],[positionMat;1]];
    transformMatInv = [[rotationMat';zeros(1,3)],[-rotationMat'*positionMat;1]];`

Link attached to code snippet https://github.com/MithunNallana/path-smoothing/blob/c610cdf2b7b881c6850343a8f0a8434323ccdfbe/code/matlab/pathsmoothbezier.m#L133-L138

Thanks,
Indraneel

**Comment by MithunNallana** [comment]
Hello @indraneelpatil 

Thanks for writing out this issue. Section V of the [paper](https://dl.acm.org/doi/10.1109/TRO.2010.2042990) provides a method to use the planar G2CBS algorithm to 3d waypoints. The above steps implement the same.

Line 135 refers to equation-21 of the [paper](https://dl.acm.org/doi/10.1109/TRO.2010.2042990).
Line 136 is a standard way to take an inverse of transformation matrix (look at eq-2.45 in [Craig](https://www.pearson.com/us/higher-education/product/Craig-Introduction-to-Robotics-Mechanics-and-Control-3rd-Edition/9780201543612.html) to understand details)

Mithun

**Comment by indraneelpatil** [comment]
Thanks for your response, closing this as answered!
